#-*-mode:makefile-gmake;indent-tabs-mode:t;tab-width:8;coding:utf-8-*-┐
#── vi: set noet ft=make ts=8 sw=8 fenc=utf-8 :vi ────────────────────┘

PKGS += TOOL_IMG_JXLTINYC

TOOL_IMG_JXLTINYC_ARTIFACTS += TOOL_IMG_JXLTINYC_A
TOOL_IMG_JXLTINYC = $(TOOL_IMG_JXLTINYC_A_DEPS) $(TOOL_IMG_JXLTINYC_A)
TOOL_IMG_JXLTINYC_A = o/$(MODE)/tool/img/jxltinyc/jxl.a
TOOL_IMG_JXLTINYC_A_HDRS = $(filter %.h,$(TOOL_IMG_JXLTINYC_A_FILES))
TOOL_IMG_JXLTINYC_A_SRCS = $(filter %.cc,$(TOOL_IMG_JXLTINYC_A_FILES))
TOOL_IMG_JXLTINYC_A_CHECKS = $(TOOL_IMG_JXLTINYC_A).pkg

TOOL_IMG_JXLTINYC_A_FILES :=					\
	$(wildcard tool/img/jxltinyc/*)

TOOL_IMG_JXLTINYC_A_OBJS = $(TOOL_IMG_JXLTINYC_A_SRCS:%.cc=o/$(MODE)/%.o)

TOOL_IMG_JXLTINYC_A_DIRECTDEPS =				\
	LIBC_INTRIN						\
	LIBC_MEM						\
	LIBC_STDIO						\
	LIBC_SYSV						\
	LIBC_TINYMATH						\
	THIRD_PARTY_LIBCXX					\
	THIRD_PARTY_LIBCXXABI					\
	THIRD_PARTY_LIBJXLTINY					\
	THIRD_PARTY_LIBUNWIND

TOOL_IMG_JXLTINYC_A_DEPS :=					\
	$(call uniq,$(foreach x,$(TOOL_IMG_JXLTINYC_A_DIRECTDEPS),$($(x))))

$(TOOL_IMG_JXLTINYC_A):					\
		tool/img/jxltinyc/				\
		$(TOOL_IMG_JXLTINYC_A).pkg			\
		$(TOOL_IMG_JXLTINYC_A_OBJS)

$(TOOL_IMG_JXLTINYC_A).pkg:					\
		$(TOOL_IMG_JXLTINYC_A_OBJS)			\
		$(foreach x,$(TOOL_IMG_JXLTINYC_A_DIRECTDEPS),$($(x)_A).pkg)

$(TOOL_IMG_JXLTINYC_A_OBJS): tool/img/jxltinyc/BUILD.mk

TOOL_IMG_JXLTINYC_LIBS = $(foreach x,$(TOOL_IMG_JXLTINYC_ARTIFACTS),$($(x)))
TOOL_IMG_JXLTINYC_SRCS = $(foreach x,$(TOOL_IMG_JXLTINYC_ARTIFACTS),$($(x)_SRCS))
TOOL_IMG_JXLTINYC_HDRS = $(foreach x,$(TOOL_IMG_JXLTINYC_ARTIFACTS),$($(x)_HDRS))
TOOL_IMG_JXLTINYC_BINS = $(foreach x,$(TOOL_IMG_JXLTINYC_ARTIFACTS),$($(x)_BINS))
TOOL_IMG_JXLTINYC_CHECKS = $(foreach x,$(TOOL_IMG_JXLTINYC_ARTIFACTS),$($(x)_CHECKS))
TOOL_IMG_JXLTINYC_OBJS = $(foreach x,$(TOOL_IMG_JXLTINYC_ARTIFACTS),$($(x)_OBJS))
TOOL_IMG_JXLTINYC_TESTS = $(foreach x,$(TOOL_IMG_JXLTINYC_ARTIFACTS),$($(x)_TESTS))

.PHONY: o/$(MODE)/tool/img/jxltinyc
o/$(MODE)/tool/img/jxltinyc: $(TOOL_IMG_JXLTINYC_CHECKS)
